TARC3_WeatherInstitute_1F_MapScripts::
	.byte 0


TARC3_Lab_F1_Rotom::
# 7 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	lock
# 8 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	faceplayer
# 9 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	playmoncry SPECIES_ROTOM, CRY_MODE_NORMAL
# 10 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	setspeaker TARC3_Lab_F1_Rotom_Text_0
# 11 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	msgbox TARC3_Lab_F1_Rotom_Text_1
# 12 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	release
	end


TARC3_Lab_F1_Pansage::
# 17 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	lock
# 18 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	faceplayer
# 19 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	playmoncry SPECIES_PANSAGE, CRY_MODE_NORMAL
# 20 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	setspeaker TARC3_Lab_F1_Pansage_Text_0
# 21 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	msgbox TARC3_Lab_F1_Pansage_Text_1
# 22 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	release
	end


TARC3_Lab_F1_Magnemite::
# 27 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	lock
# 28 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	faceplayer
# 29 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	playmoncry SPECIES_MAGNEMITE, CRY_MODE_NORMAL
# 30 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	setspeaker TARC3_Lab_F1_Magnemite_Text_0
# 31 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	msgbox TARC3_Lab_F1_Magnemite_Text_1
# 32 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	release
	end


TARC3_Lab_F1_Metagross::
# 37 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	lock
# 38 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	faceplayer
# 39 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	playmoncry SPECIES_METAGROSS, CRY_MODE_NORMAL
# 40 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	setspeaker TARC3_Lab_F1_Metagross_Text_0
# 41 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	msgbox TARC3_Lab_F1_Metagross_Text_1
# 42 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	release
	end


TARC3_Lab_F1_Rotom_Text_0:
# 10 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	.string "Rotom$"

TARC3_Lab_F1_Rotom_Text_1:
# 11 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	.string "Bzzz... Bzzz...\pWe are charging the reactor!$"

TARC3_Lab_F1_Pansage_Text_0:
# 20 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	.string "Pansage$"

TARC3_Lab_F1_Pansage_Text_1:
# 21 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	.string "I am the most skilled employee\nof this facility.\pDon't disturb me!$"

TARC3_Lab_F1_Magnemite_Text_0:
# 30 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	.string "Magnemite$"

TARC3_Lab_F1_Magnemite_Text_1:
# 31 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	.string "I am watching the facility's\nsecurity system.\pDo not tamper with the equipment!$"

TARC3_Lab_F1_Metagross_Text_0:
# 40 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	.string "Metagross$"

TARC3_Lab_F1_Metagross_Text_1:
# 41 "data/maps/TARC3_WeatherInstitute_1F/scripts.pory"
	.string "I will give some helpful advice!$"
