#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

#define MUGSHOT_NONE    0
#define MUGSHOT_TEST    1
#define MUGSHOT_SUNKERN 2
#define MUGSHOT_WOOPER  3
#define MUGSHOT_TORKOAL 4
#define MUGSHOT_XATU    5
#define MUGSHOT_WHIMSICOTT 6
#define MUGSHOT_COUNT   7

#define EMOTE_NORMAL  0
#define EMOTE_ALT     1
#define EMOTE_COUNT   2

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
