gText_Birch_Welcome::
	.string "Hello, explorer!\p"
	.string "Welcome to the Pokémon Escape\n"
	.string "Room challenge NATIONAL HISTORY\l"
	.string "MUSEUM.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I will give you all information\n"
	.string "you may need to start your \l"
	.string "adventure.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Your task is simple.\p"
	.string "You need to make it out of the\n"
	.string "NATIONAL HISTORY MUSEUM.\p"
	.string "To do so you will need to develop\n"
	.string "unique tactics to battle your\l"
	.string "opponents, solve puzzles and make\l"
	.string "the right decisions based on all\l"
	.string "information available.\p"
	.string "If you are stuck you can approach\n"
	.string "the Game Master NPC for help.\p"
	.string "This challenge can be completed\n"
	.string "without any savegame resets.\l"
	.string "Worst case is that you have to\l"
	.string "approach the Game Master to continue.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "So tell me who you are.\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, I hope you are ready!\p"
	.string "I wish you good luck!\p"
	.string "Your play time starts NOW.\p"
	.string "$"
