gText_Birch_Welcome::
	.string "Hi, explorer!\p"
	.string "Welcome to the Pokémon Escape\n"
	.string "Room challenge NATIONAL HISTORY\n"
	.string "MUSEUM.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "I will give you all information\n"
	.string "you may need to start your \n"
	.string "adventure.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Your task is simple.\p"
	.string "You need to make it out of the\n"
	.string "NATIONAL HISTORY MUSEUM.\p"
	.string "To do so you will need to develop\n"
	.string "unique tactics to battle your\n"
	.string "opponents and make the right\n"
	.string "decisions based on all information\n"
	.string "available.\p"
	
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
