Text_BootUpPC:
	.string "{PLAYER} booted up the PC.$"

gText_WhichPCShouldBeAccessed::
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC::
	.string "Accessed SOMEONE'S PC.$"

gText_StorageSystemOpened::
	.string "POKéMON Storage System opened.$"

gText_AccessedPlayersPC::
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedLanettesPC::
	.string "Accessed LANETTE's PC.$"

Text_BootUpPCDamaged:
	.string "ADMIN: The Pokemon storage \n"
	.string "system is currently corrupted.$"

gText_NoStorageSystem::
	.string "ADMIN: Can't access the \n"
	.string "Pokemon storage system.$"
