#ifndef GUARD_BATTLE_RULES_H
#define BATTLE_RULES_H

void IncrementBattleRuleRerollCounter(void);
void IncrementTypeRerollCounter(void);
u8 GetRandomBattleRuleSeeded(void);

enum battleRules {
    BATTLERULE_BANNEDTYPE_NORMAL,
    BATTLERULE_BANNEDTYPE_FIGHTING,
    BATTLERULE_BANNEDTYPE_FLYING,
    BATTLERULE_BANNEDTYPE_POISON,
    BATTLERULE_BANNEDTYPE_GROUND,
    BATTLERULE_BANNEDTYPE_ROCK,
    BATTLERULE_BANNEDTYPE_BUG,
    BATTLERULE_BANNEDTYPE_GHOST,
    BATTLERULE_BANNEDTYPE_STEEL,
    BATTLERULE_BANNEDTYPE_MYSTERY, // inactive, only used to match the general Type enum
    BATTLERULE_BANNEDTYPE_FIRE,
    BATTLERULE_BANNEDTYPE_WATER,
    BATTLERULE_BANNEDTYPE_GRASS,
    BATTLERULE_BANNEDTYPE_ELECTRIC,
    BATTLERULE_BANNEDTYPE_PSYCHIC,
    BATTLERULE_BANNEDTYPE_ICE,
    BATTLERULE_BANNEDTYPE_DRAGON,
    BATTLERULE_BANNEDTYPE_DARK,
    BATTLERULE_BANNEDTYPE_FAIRY,
    BATTLERULE_BANNEDMOVETYPE_NORMAL,
    BATTLERULE_BANNEDMOVETYPE_FIGHTING,
    BATTLERULE_BANNEDMOVETYPE_FLYING,
    BATTLERULE_BANNEDMOVETYPE_POISON,
    BATTLERULE_BANNEDMOVETYPE_GROUND,
    BATTLERULE_BANNEDMOVETYPE_ROCK,
    BATTLERULE_BANNEDMOVETYPE_BUG,
    BATTLERULE_BANNEDMOVETYPE_GHOST,
    BATTLERULE_BANNEDMOVETYPE_STEEL,
    BATTLERULE_BANNEDMOVETYPE_MYSTERY, // inactive, only used to match the general Type enum
    BATTLERULE_BANNEDMOVETYPE_FIRE,
    BATTLERULE_BANNEDMOVETYPE_WATER,
    BATTLERULE_BANNEDMOVETYPE_GRASS,
    BATTLERULE_BANNEDMOVETYPE_ELECTRIC,
    BATTLERULE_BANNEDMOVETYPE_PSYCHIC,
    BATTLERULE_BANNEDMOVETYPE_ICE,
    BATTLERULE_BANNEDMOVETYPE_DRAGON,
    BATTLERULE_BANNEDMOVETYPE_DARK,
    BATTLERULE_BANNEDMOVETYPE_FAIRY,
    BATTLERULE_NOHEALING,
    BATTLERULE_NOCRITS,
    BATTLERULE_NORECOIL,
    BATTLERULE_NOSTAB,
    BATTLERULE_ONLYSTAB,
    BATTLERULE_NOSUPEREFFECTIVE,
    BATTLERULE_1HP,
    BATTLERULE_1PP,
    BATTLERULE_NOSAMESEX,
    BATTLERULE_NOSWITCHING,
    BATTLERULE_PERISHCOUNT,
    BATTLERULE_SWITCHMOVES,
    BATTLERULE_NOPRIO,
    BATTLERULE_NOHELDITEMS,
    BATTLERULE_NOABILITY,
    BATTLERULE_NOSTATUS,
    BATTLERULE_SHAREDDAMAGE,
    BATTLERULE_NOSETUP,
    BATTLERULE_TRICKROOM,
    BATTLERULE_BANNEDMOVECAT_PHYSICAL,
    BATTLERULE_BANNEDMOVECAT_SPECIAL,
    BATTLERULE_BANNEDMOVECAT_STATUS,
    BATTLERULE_INVERSE,
    BATTLERULE_FIRSTMOVEONLY,
    BATTLERULE_TRUANT,
    BATTLERULE_NOMISSES
};

enum battleRuleCategories {
    BATTLERULE_CATEGORY_SENDOUT,
    BATTLERULE_CATEGORY_USEMOVE,
    BATTLERULE_CATEGORY_MOVEEFFECT,
    BATTLERULE_CATEGORY_SWITCHOUT,
    BATTLERULE_CATEGORY_ACTIVATE_ITEM,
    BATTLERULE_CATEGORY_ACTIVATE_ABILITY,
    BATTLERULE_CATEGORY_MULTIPLE,
    BATTLERULE_CATEGORY_GENERAL
};

struct BattleRule
{
    u8 weight; // currently not used;
    bool8 enabled;
    u8 category;
};

extern const struct BattleRule gBattleRules[];

#endif // BATTLE_RULES_H
